## Regression:
* Searches for realtionship among variables 
* Finds the function that maps variables (inputs/feaures) t dependent variables (output/responses)
* Dependent variable ususally continuous and unbounded

## Linear Regression

y = $\theta0$x0 

# Regression Performance

### Types of regression 
* Linear regression (univariate)
* Multiple variable Linear Regression (multivariate)
* Polynomial Linear Regression (introduce powers and nonlinear terms)

### Implementation

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [11]:
x = np.array([5, 15, 25, 45, 37, 67, 55]).reshape((-1,1))
y = np.array([110,220,310,560, 412, 732, 640]).reshape((-1,1))

In [12]:
x.shape, y.shape

((7, 1), (7, 1))

In [13]:
model = LinearRegression().fit(x,y)
r_sq = model.score(x,y)
print("R squared: ", r_sq)

R squared:  0.9911353350742254


In [14]:
print("Intercept x0: ", model.intercept_)
print("Slope theta1: ", model.coef_)

Intercept x0:  [59.80273437]
Slope theta1:  [[10.30273438]]


In [17]:
y_pred = model.predict(x)
y_pred

array([[111.31640625],
       [214.34375   ],
       [317.37109375],
       [523.42578125],
       [441.00390625],
       [750.0859375 ],
       [626.453125  ]])

In [18]:
y_pred1 = model.intercept_ + model.coef_*x
y_pred1

array([[111.31640625],
       [214.34375   ],
       [317.37109375],
       [523.42578125],
       [441.00390625],
       [750.0859375 ],
       [626.453125  ]])

In [19]:
y_pred == y_pred1

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [23]:
y_pred_new = model.predict(np.arange(10).reshape(-1,1))
y_pred_new

array([[ 59.80273437],
       [ 70.10546875],
       [ 80.40820312],
       [ 90.7109375 ],
       [101.01367187],
       [111.31640625],
       [121.61914062],
       [131.921875  ],
       [142.22460937],
       [152.52734375]])

In [26]:
x = np.array([[5,45,78], [15,37,38], [25,47,29], [45,37,89], [37,26,18], [67,17,29], [55,16,18]])
y = np.array([110,220,310,560, 412, 732, 640])

In [27]:
model = LinearRegression().fit(x,y)
r_sq = model.score(x,y)
print("R squared: ", r_sq)

R squared:  0.9951568985588507


In [28]:
print("Intercept x0: ", model.intercept_)
print("Slope theta1: ", model.coef_)

Intercept x0:  26.30962656415403
Slope theta1:  [10.56790272  0.04403182  0.53015946]


In [29]:
y_pred = model.predict(x)
y_pred

array([122.48300959, 206.60340396, 307.95131421, 550.67861795,
       428.00972471, 750.48227404, 617.79165553])

### Polynomial Regression

In [31]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [32]:
x = np.array([5, 15, 25, 45, 37, 67, 55]).reshape((-1,1))
y = np.array([110,220,310,560, 412, 732, 640]).reshape((-1,1))

In [33]:
transformer = PolynomialFeatures(degree = 2, include_bias = False)
transformer.fit(x)
x_ = transformer.transform(x)
print(x_)
model = LinearRegression().fit(x_,y)
r_sq = model.score(x_,y)
print("R squared: ", r_sq)
print("Intercept x0: ", model.intercept_)
print("Slope theta1: ", model.coef_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  45. 2025.]
 [  37. 1369.]
 [  67. 4489.]
 [  55. 3025.]]
R squared:  0.991415533081388
Intercept x0:  [51.64533429]
Slope theta1:  [[ 1.09827006e+01 -9.52302405e-03]]


include bias = True in polynomial feature transformer

In [35]:
x = np.array([5, 15, 25, 45, 37, 67, 55]).reshape((-1,1))
y = np.array([110,220,310,560, 412, 732, 640]).reshape((-1,1))

In [36]:
transformer = PolynomialFeatures(degree = 2, include_bias = True)
transformer.fit(x)
x_ = transformer.transform(x)
print(x_)
model = LinearRegression().fit(x_,y)
r_sq = model.score(x_,y)
print("R squared: ", r_sq)
print("Intercept x0: ", model.intercept_)
print("Slope theta1: ", model.coef_)

[[1.000e+00 5.000e+00 2.500e+01]
 [1.000e+00 1.500e+01 2.250e+02]
 [1.000e+00 2.500e+01 6.250e+02]
 [1.000e+00 4.500e+01 2.025e+03]
 [1.000e+00 3.700e+01 1.369e+03]
 [1.000e+00 6.700e+01 4.489e+03]
 [1.000e+00 5.500e+01 3.025e+03]]
R squared:  0.991415533081388
Intercept x0:  [51.64533429]
Slope theta1:  [[ 0.00000000e+00  1.09827006e+01 -9.52302405e-03]]
