#### Roll No. : J014
#### Name : Ankita Dasgupta
#### Machine Learning Assignment 2

In [6]:
import numpy as np

A = np.random.randint(1,40,9)
A = A.reshape((3,3))
B = np.random.randint(1,40,9)
B = B.reshape((3,3))
C = np.random.randint(1,40,9)
C = C.reshape((3,3))
I = np.identity(3)

print('Matrix A : \n', A)
print('Matrix B : \n', B)
print('Matrix C : \n', C)
print('Identity Matrix : \n', I)

Matrix A : 
 [[ 5  9  6]
 [39  9 29]
 [39 15 27]]
Matrix B : 
 [[31 16 29]
 [ 8 32 26]
 [ 9 12 11]]
Matrix C : 
 [[16 16 37]
 [26 33 20]
 [20 26 25]]
Identity Matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Proving all the multiplication properties for matrices
#### Commutative property:
#### A.B = B.A

In [7]:
A_dot_B = A.dot(B)
B_dot_A = B.dot(A)
print('A.B : \n', A_dot_B)
print('B.A : \n', B_dot_A)

A.B : 
 [[ 281  440  445]
 [1542 1260 1684]
 [1572 1428 1818]]
B.A : 
 [[1910  858 1433]
 [2302  750 1678]
 [ 942  354  699]]


#### A.B is not equal to B.A
#### Therefore commutative property is not applicable for matrix multiplication

#### Associative Property:
#### (A*B)*C=A*(B*C)

In [8]:
print('(A.B).C : \n', np.dot(A, B).dot(C))
print('A.(B.C) : \n', A.dot(np.dot(B, C)))

(A.B).C : 
 [[ 24836  30586  30322]
 [ 91112 110036 124354]
 [ 98640 119544 132174]]
A.(B.C) : 
 [[ 24836  30586  30322]
 [ 91112 110036 124354]
 [ 98640 119544 132174]]


#### Distributive Property:
#### A ( B + C ) = A B + A C

In [9]:
print("A.(B+C) : \n", np.dot(A, B+C))
print('A.B + A.C : \n', np.dot(A, B) + np.dot(A, C))

A.(B+C) : 
 [[ 715  973  960]
 [2980 2935 4032]
 [3126 3249 4236]]
A.B + A.C : 
 [[ 715  973  960]
 [2980 2935 4032]
 [3126 3249 4236]]


#### Multiplicative Identity Property:
#### AI = IA

In [10]:
print('A.I : \n', np.dot(A, I))
print('I.A :\n', np.dot(I, A))

A.I : 
 [[ 5.  9.  6.]
 [39.  9. 29.]
 [39. 15. 27.]]
I.A :
 [[ 5.  9.  6.]
 [39.  9. 29.]
 [39. 15. 27.]]


#### Multiplicative Property of Zero:
#### 0 A  = A 0 = 0

In [11]:
O = np.zeros(9).reshape(3, 3)
print('A.0 : \n', np.dot(A, O))
print('0.A : \n', np.dot(O, A))

A.0 : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0.A : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Dimension Property:
#### The product of an m × n and n×k matrix is an m × k 

In [17]:
m,n,k = 3,6,4
mat_mn = np.random.randint(1,40,m*n)
mat_mn = mat_mn.reshape((m,n))
mat_nk = np.random.randint(1,40,n*k)
mat_nk = mat_nk.reshape((n,k))
mat_mult = np.dot(mat_mn, mat_nk)
result_x, result_y = mat_mult.shape
print(mat_mn)
print("\tX")
print(mat_nk)
print("\t=")
print(mat_mult,"\n")
print(f' {m}x{n} matrix X {n}x{k} matrix = {result_x}x{result_y} matrix')

[[35 12 33 28 28 25]
 [18 16 22 34 33 24]
 [11 20 36 39  3 12]]
	X
[[26  1 25  7]
 [ 9 14 31 32]
 [24 25 19  4]
 [ 7 21 21 37]
 [26  5 15  6]
 [36  4 13 34]]
	=
[[3634 1856 3207 2815]
 [3100 1767 2885 2998]
 [2113 2073 2599 2730]] 

 3x6 matrix X 6x4 matrix = 3x4 matrix


#### Matrix Inverse:

In [24]:
print("A:\n", A)
print("INV(A):\n", np.linalg.inv(A))

A:
 [[ 5  9  6]
 [39  9 29]
 [39 15 27]]
INV(A):
 [[-0.16753927 -0.13350785  0.18062827]
 [ 0.06806283 -0.08638743  0.07766143]
 [ 0.20418848  0.2408377  -0.26701571]]


#### Comparison between numpy and looping

In [26]:
import time
size = 10000
np_mat_A = np.random.randn(size, size)
np_mat_B = np.random.randn(size, size)
list_mat_A = [list(i) for i in np_mat_A]
list_mat_B = [list(i)for i in np_mat_B]
start_loop = time.time()
list_mat_C = []
for i in range(size) :
    row = []
    for j in range(size) :
        row.append(list_mat_A[i][j] + list_mat_B[i][j])
    list_mat_C.append(row)
end_loop = time.time()
start_np = time.time()
np_mat_C = np_mat_A + np_mat_B
end_np = time.time()
print('Time for loops : ', end_loop - start_loop)
print('Time for numpy : ', end_np - start_np)

Time for loops :  161.18343591690063
Time for numpy :  18.771825790405273


#### Hence, we can say that using Numpy is much faster than using loops